/*
 * <insert header here>
 */

#ifndef _DEVICES_H
#define _DEVICES_H

#define MAG_VENDOR_ID	0x1CD7

/* Driver supports the following capture devices */

#define MAG_PCI_DEV_AIO	0x0002
#define MAG_PCI_DEV_DVI		0x0003
#define MAG_PCI_DEV_HDMI	0x0004
#define MAG_PCI_DEV_SDI		0x0005
#define MAG_PCI_DEV_DUALSDI	0x0006
#define MAG_PCI_DEV_DUALDVI	0x0007
#define MAG_PCI_DEV_DUALHDMI	0x0008
#define MAG_PCI_DEV_QUADSDI	0x0009
#define MAG_PCI_DEV_QUADHDMI	0x0010
#define MAG_PCI_DEV_MINIHDMI	0x0011
#define MAG_PCI_DEV_HDMI4K	0x0012
#define MAG_PCI_DEV_MINISDI	0x0013

static const struct pci_device_id magewell_pci_tbl[] = {
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_AIO) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_DVI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_HDMI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_SDI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_DUALSDI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_DUALDVI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_DUALHDMI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_QUADSDI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_QUADHDMI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_MINIHDMI) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_HDMI4K) },
	{ PCI_DEVICE(MAG_VENDOR_ID, MAG_PCI_DEV_MINISDI) },
	{ 0, }
};

#endif
