

////////////////////////////////////////////////////////////////////////////////
// I2C address
#define IO_MAP_ADDR                                                     0x98
#define CEC_MAP_ADDR                                            0x80
#define INFOFRAME_MAP_ADDR                                      0x7C
#define DPLL_MAP_ADDR                                           0x4C
#define REPEATER_MAP_ADDR                                       0x64
#define EDID_MAP_ADDR                                           0x6C
#define HDMI_MAP_ADDR                                           0x68
#define CP_MAP_ADDR                                                     0x44


////////////////////////////////////////////////////////////////////////////////
// IO map registers
#define VIDEO_STANDARD_REG                                      0x00
#define PRIMARY_MODE_REG                                        0x01
#define IO_REG_02_REG                                           0x02
#define IO_REG_03_REG                                           0x03
#define IO_REG_04_REG                                           0x04
#define IO_REG_05_REG                                           0x05
#define IO_REG_06_REG                                           0x06
#define IO_POWER_DOWN_1_REG                                     0x0B
#define IO_POWER_DOWN_2_REG                                     0x0C
#define IO_REG_12_REG                                           0x12
#define IO_DR_STR_REG                                           0x14
#define IO_TRI_STATE_REG                                        0x15
#define IO_PLL_DIV_HIGH_REG                                     0x16
#define IO_PLL_DIV_LOW_REG                                      0x17
#define IO_LLC_DLL_REG                                          0x19
#define ALSB_CONTROL_REG                                        0x1B
#define HPA_1_REG                                                       0x20
#define HPA_2_REG                                                       0x21
#define IO_REG_30_REG                                           0x30
#define IO_REG_33_REG                                           0x33
#define INT_STATUS_REG                                          0x3F
#define INT1_CONFIGURATION_REG                          0x40
#define INT2_CONFIGURATION_REG                          0x41
#define STATUS1_RAW_REG                                         0x42
#define STATUS1_ST_REG                                          0x43
#define STATUS1_CLR_REG                                         0x44
#define STATUS1_MB2_REG                                         0x45
#define STATUS1_MB1_REG                                         0x46
#define STATUS2_RAW_REG                                         0x47
#define STATUS2_ST_REG                                          0x48
#define STATUS2_CLR_REG                                         0x49
#define STATUS2_MB2_REG                                         0x4A
#define STATUS2_MB1_REG                                         0x4B
#define STATUS3_RAW_REG                                         0x5B
#define STATUS3_ST_REG                                          0x5C
#define STATUS3_CLR_REG                                         0x5D
#define STATUS3_MB2_REG                                         0x5E
#define STATUS3_MB1_REG                                         0x5F
#define HDMI_LVL_RAW_STATUS_1_REG                       0x60
#define HDMI_LVL_INT_STATUS_1_REG                       0x61
#define HDMI_LVL_INT_CLR_1_REG                          0x62
#define HDMI_LVL_INT2_MASKB_1_REG                       0x63
#define HDMI_LVL_INT_MASKB_1_REG                        0x64
#define HDMI_LVL_RAW_STATUS_2_REG                       0x65
#define HDMI_LVL_INT_STATUS_2_REG                       0x66
#define HDMI_LVL_INT_CLR_2_REG                          0x67
#define HDMI_LVL_INT2_MASKB_2_REG                       0x68
#define HDMI_LVL_INT_MASKB_2_REG                        0x69
#define HDMI_LVL_RAW_STATUS_3_REG                       0x6A
#define HDMI_LVL_INT_STATUS_3_REG                       0x6B
#define HDMI_LVL_INT_CLR_3_REG                          0x6C
#define HDMI_LVL_INT2_MASKB_3_REG                       0x6D
#define HDMI_LVL_INT_MASKB_3_REG                        0x6E
#define HDMI_LVL_RAW_STATUS_4_REG                       0x6F
#define HDMI_LVL_INT_STATUS_4_REG                       0x70
#define HDMI_LVL_INT_CLR_4_REG                          0x71
#define HDMI_LVL_INT2_MASKB_4_REG                       0x72
#define HDMI_LVL_INT_MASKB_4_REG                        0x73
#define HDMI_EDG_RAW_STATUS_1_REG                       0x79
#define HDMI_EDG_INT_STATUS_1_REG                       0x7A
#define HDMI_EDG_INT_CLR_1_REG                          0x7B
#define HDMI_EDG_INT2_MASKB_1_REG                       0x7C
#define HDMI_EDG_INT_MASKB_1_REG                        0x7D
#define HDMI_EDG_RAW_STATUS_2_REG                       0x7E
#define HDMI_EDG_INT_STATUS_2_REG                       0x7F
#define HDMI_EDG_INT_CLR_2_REG                          0x80
#define HDMI_EDG_INT2_MASKB_2_REG                       0x81
#define HDMI_EDG_INT_MASKB_2_REG                        0x82
#define HDMI_EDG_RAW_STATUS_3_REG                       0x83
#define HDMI_EDG_INT_STATUS_3_REG                       0x84
#define HDMI_EDG_INT_CLR_3_REG                          0x85
#define HDMI_EDG_INT2_MASKB_3_REG                       0x86
#define HDMI_EDG_INT_MASKB_3_REG                        0x87
#define HDMI_EDG_RAW_STATUS_4_REG                       0x88
#define HDMI_EDG_INT_STATUS_4_REG                       0x89
#define HDMI_EDG_INT_CLR_4_REG                          0x8A
#define HDMI_EDG_INT2_MASKB_4_REG                       0x8B
#define HDMI_EDG_INT_MASKB_4_REG                        0x8C
#define HDMI_EDG_RAW_STATUS_5_REG                       0x8D
#define HDMI_EDG_INT_STATUS_5_REG                       0x8E
#define HDMI_EDG_INT_CLR_5_REG                          0x8F
#define HDMI_EDG_INT2_MASKB_5_REG                       0x90
#define HDMI_EDG_INT_MASKB_5_REG                        0x91
#define CEC_STATUS1_RAW_REG                                     0x92
#define CEC_STATUS1_INT_STATUS_REG                      0x93
#define CEC_STATUS1_INT_CLEARREG                        0x94
#define CEC_STATUS1_INT2_MASKB_REG                      0x95
#define CEC_STATUS1_INT1_MASKB_REG                      0x96
#define CEC_RAW_STATUS2_REG                                     0x97
#define CEC_INTERRUPT_STATUS2_REG                       0x98
#define CEC_INTERRUPT_CLEAR2_REG                        0x99
#define CEC_INTERRUPT2_MASKB_REG                        0x9A
#define CEC_INTERRUPT_MASKB_REG                         0x9B
#define IO_REG_E0_REG                                           0xE0
#define IO_REG_E7_REG                                           0xE7
#define RD_INFO_HIGH_REG                                        0xEA
#define RD_INFO_LOW_REG                                         0xEB
#define CEC_SLAVE_ADDRESS_REG                           0xF4
#define INFOFRAME_SLAVE_ADDRESS_REG                     0xF5
#define DPLL_SLAVE_ADDRESS_REG                          0xF8
#define KSV_SLAVE_ADDRESS_REG                           0xF9
#define EDID_SLAVE_ADDRESS_REG                          0xFA
#define HDMI_SLAVE_ADDRESS_REG                          0xFB
#define CP_SLAVE_ADDRESS_REG                            0xFD
#define RESET_REG                                                       0xFF


////////////////////////////////////////////////////////////////////////////////
// DPLL map registers
#define MCLK_FS_REG                                                     0xB5

////////////////////////////////////////////////////////////////////////////////
// HDMI map registers
#define HDMI_REGISTER_00H_REG                           0x00
#define HDMI_REGISTER_01H_REG                           0x01
#define HDMI_REGISTER_BG_PORT_ENABLE_REG        0x02
#define HDMI_REGISTER_03H_REG                           0x03
#define HDMI_REGISTER_04H_REG                           0x04
#define HDMI_REGISTER_05H_REG                           0x05
#define LINE_WIDTH_1_REG                                        0x07
#define LINE_WIDTH_2_REG                                        0x08
#define LINE_FIELD_0_HEIGHT_1_REG                       0x09
#define LINE_FIELD_0_HEIGHT_2_REG                       0x0A
#define LINE_FIELD_1_HEIGHT_1_REG                       0x0B
#define LINE_FIELD_1_HEIGHT_2_REG                       0x0C
#define HDMI_REGISTER_0DH_REG                           0x0D
#define AUDIO_MUTE_SPEED_REG                            0x0F
#define HDMI_REGISTER_10H_REG                           0x10
#define AUDIO_FIFO_FULL_THRESHOLD_REG           0x11
#define AUDIO_FIFO_EMPTY_THRESHOLD_REG          0x12
#define AUDIO_COAST_MASK_REG                            0x13
#define MUTE_MASK_21_16_REG                                     0x14
#define MUTE_MASK_15_8_REG                                      0x15
#define MUTE_MASK_7_0_REG                                       0x16
#define PACKETS_DETECTED_2_REG                          0x18
#define PACKETS_DETECTED_3_REG                          0x19
#define MUTE_CTRL_REG                                           0x1A
#define DEEPCOLOR_FIFO_DEBUG_1_REG                      0x1B
#define DEEPCOLOR_FIFO_DEBUG_2_REG                      0x1C
#define HDMI_REGISTER_1DH_REG                           0x1D
#define TOTAL_LINE_WIDTH_1_REG                          0x1E
#define TOTAL_LINE_WIDTH_2_REG                          0x1F
#define HSYNC_FRONT_PORCH_1_REG                         0x20
#define HSYNC_FRONT_PORCH_2_REG                         0x21
#define HSYNC_PULSE_WIDTH_1_REG                         0x22
#define HSYNC_PULSE_WIDTH_2_REG                         0x23
#define HSYNC_BACK_PORCH_1_REG                          0x24
#define HSYNC_BACK_PORCH_2_REG                          0x25
#define FIELD0_TOTAL_HEIGHT_1_REG                       0x26
#define FIELD0_TOTAL_HEIGHT_2_REG                       0x27
#define FIELD1_TOTAL_HEIGHT_1_REG                       0x28
#define FIELD1_TOTAL_HEIGHT_2_REG                       0x29
#define FIELD0_VS_FRONT_PORCH_1_REG                     0x2A
#define FIELD0_VS_FRONT_PORCH_2_REG                     0x2B
#define FIELD1_VS_FRONT_PORCH_1_REG                     0x2C
#define FIELD1_VS_FRONT_PORCH_2_REG                     0x2D
#define FIELD0_VS_PULSE_WIDTH_1_REG                     0x2E
#define FIELD0_VS_PULSE_WIDTH_2_REG                     0x2F
#define FIELD1_VS_PULSE_WIDTH_1_REG                     0x30
#define FIELD1_VS_PULSE_WIDTH_2_REG                     0x31
#define FIELD0_VS_BACK_PORCH_1_REG                      0x32
#define FIELD0_VS_BACK_PORCH_2_REG                      0x33
#define FIELD1_VS_BACK_PORCH_1_REG                      0x34
#define FIELD1_VS_BACK_PORCH_2_REG                      0x35
#define CHANNEL_STATUS_DATA_1_REG                       0x36
#define CHANNEL_STATUS_DATA_2_REG                       0x37
#define CHANNEL_STATUS_DATA_3_REG                       0x38
#define CHANNEL_STATUS_DATA_4_REG                       0x39
#define CHANNEL_STATUS_DATA_5_REG                       0x3A
#define HDMI_REGISTER_3CH_REG                           0x3C
#define HDMI_REGISTER_40H_REG                           0x40
#define HDMI_REGISTER_41H_REG                           0x41
#define HDMI_REGISTER_47H_REG                           0x47
#define HDMI_REGISTER_48H_REG                           0x48
#define HDMI_REGISTER_50H_REG                           0x50
#define TMDSFREQ_1_REG                                          0x51
#define TMDSFREQ_2_REG                                          0x52
#define HDMI_COLORSPACE_REG                                     0x53
#define FILT_5V_DET_REG                                         0x56
#define HDMI_REGISTER_5AH_REG                           0x5A
#define CTS_N_1_REG                                                     0x5B
#define CTS_N_2_REG                                                     0x5C
#define CTS_N_3_REG                                                     0x5D
#define CTS_N_4_REG                                                     0x5E
#define CTS_N_5_REG                                                     0x5F
#define HPA_CTRL_REG                                            0x6C
#define I2S_DSD_MAP_REG                                         0x6D
#define DST_MAP_REG                                                     0x6E
#define CLOCK_TERM_CTRL_REG                                     0x83
#define BG_TMDSFREQ_1_REG                                       0xE0
#define BG_TMDSFREQ_2_REG                                       0xE1
#define BG_LINE_WIDTH_HIGH_REG                          0xE2
#define BG_LINE_WIDTH_LOW_REG                           0xE3
#define BG_TOTAL_LINE_WIDTH_HIGH_REG            0xE4
#define BG_TOTAL_LINE_WIDTH_LOW_REG                     0xE5
#define BG_FIELD_HIGHT_HIGH_REG                         0xE6
#define BG_FIELD_HIGHT_LOW_REG                          0xE7
#define BG_TOTAL_FIELD_HIGHT_HIGH_REG           0xE8
#define BG_TOTAL_FIELD_HIGHT_LOW_REG            0xE9
#define BG_VIDEO_FORMAT_REG                                     0xEA
#define BG_HDMI_MODE_REG                                        0xEB
#define BG_AUDIO_STATUS_REG                                     0xEE
#define BG_HEADER_REQUESTED_REG                         0xEF
#define BG_HEADER_BYTE1_REG                                     0xF0
#define BG_PACKET_BYTE1_REG                                     0xF1
#define BG_PACKET_BYTE2_REG                                     0xF2
#define BG_PACKET_BYTE3_REG                                     0xF3
#define BG_PACKET_BYTE4_REG                                     0xF4
#define BG_PACKET_BYTE5_REG                                     0xF5
#define BG_VALID_PACKET_REG                                     0xF6

////////////////////////////////////////////////////////////////////////////////
// REPEATER map registers
#define BKSV_1_REG                                                      0x00
#define BKSV_5_REG                                                      0x04
#define RI_1_REG                                                        0x08
#define RI_2_REG                                                        0x09
#define PJ_REG                                                          0x0A
#define AKSV_1_REG                                                      0x10
#define AKSV_5_REG                                                      0x14
#define AINFO_REG                                                       0x15
#define AN_1_REG                                                        0x18
#define AN_8_REG                                                        0x1F
#define SHA_A_1_REG                                                     0x20
#define SHA_A_4_REG                                                     0x23
#define SHA_B_1_REG                                                     0x24
#define SHA_B_4_REG                                                     0x27
#define SHA_C_1_REG                                                     0x28
#define SHA_C_4_REG                                                     0x2B
#define SHA_D_1_REG                                                     0x2C
#define SHA_D_4_REG                                                     0x2F
#define SHA_E_1_REG                                                     0x30
#define SHA_E_4_REG                                                     0x33
#define BCAPS_REG                                                       0x40
#define BSTATUS_1_REG                                           0x41
#define BSTATUS_2_REG                                           0x42
#define SPA_PORT_B_1_REG                                        0x52
#define SPA_PORT_B_2_REG                                        0x53
#define PORT_B_CHECKSUM_REG                                     0x61
#define SPA_LOCATION_REG                                        0x70
#define KSV_LIST_READY_REG                                      0x71
#define IROM_BIST_REG                                           0x72
#define VGA_EDID_ENABLE_CPU_REG                         0x73
#define HDCP_EDID_CONTROLS                                      0x74
#define EDID_DEBUG_2_REG                                        0x76
#define EDID_LOAD_STORE_REG                                     0x77
#define EDID_DEBUG_3_REG                                        0x78
#define HDCP_MAP_SELECT_REG                                     0x79
#define EDID_CTRL_REG                                           0x7A
#define KSV_0_1_REG                                                     0x80
#define KSV_0_128_REG                                           0xFF


////////////////////////////////////////////////////////////////////////////////
// INFOFRAME map registers
#define AVI_INF_PB_0_1_REG                                      0x00
#define AVI_INF_PB_0_28_REG                                     0x1B
#define AUD_INF_PB_0_1_REG                                      0x1C
#define AUD_INF_PB_0_14_REG                                     0x29
#define SPD_INF_PB_0_1_REG                                      0x2A
#define SPD_INF_PB_0_28_REG                                     0x45
#define MS_INF_PB_0_1_REG                                       0x46
#define MS_INF_PB_0_14_REG                                      0x53
#define VS_INF_PB_0_1_REG                                       0x54
#define VS_INF_PB_0_28_REG                                      0x6F
#define ACP_PB_0_1_REG                                          0x70
#define ACP_PB_0_28_REG                                         0x8B
#define ISRC1_PB_0_1_REG                                        0x8C
#define ISRC1_PB_0_28_REG                                       0xA7
#define ISRC2_PB_0_1_REG                                        0xA8
#define ISRC2_PB_0_28_REG                                       0xC3
#define GAMUT_MDATA_PB_0_1_REG                          0xC4
#define GAMUT_MDATA_PB_0_28_REG                         0xDF
#define AVI_PACKET_ID_REG                                       0xE0
#define AVI_INF_VERS_REG                                        0xE1
#define AVI_INF_LEN_REG                                         0xE2
#define AUD_PACKET_ID_REG                                       0xE3
#define AUD_INF_VERS_REG                                        0xE4
#define AUD_INF_LEN_REG                                         0xE5
#define SPD_PACKET_ID_REG                                       0xE6
#define SPD_INF_VERS_REG                                        0xE7
#define SPD_INF_LEN_REG                                         0xE8
#define MS_PACKET_ID_REG                                        0xE9
#define MS_INF_VERS_REG                                         0xEA
#define MS_INF_LEN_REG                                          0xEB
#define VS_PACKET_ID_REG                                        0xEC
#define VS_INF_VERS_REG                                         0xED
#define VS_INF_LEN_REG                                          0xEE
#define ACP_PACKET_ID_REG                                       0xEF
#define ACP_TYPE_REG                                            0xF0
#define ACP_HEADER2_REG                                         0xF1
#define ISRC1_PACKET_ID_REG                                     0xF2
#define ISRC1_HEADER1_REG                                       0xF3
#define ISRC1_HEADER2_REG                                       0xF4
#define ISRC2_PACKET_ID_REG                                     0xF5
#define ISRC2_HEADER1_REG                                       0xF6
#define ISRC2_HEADER2_REG                                       0xF7
#define GAMUT_PACKET_ID_REG                                     0xF8
#define GAMUT_HEADER1_REG                                       0xF9
#define GAMUT_HEADER2_REG                                       0xFA


////////////////////////////////////////////////////////////////////////////////
// CP map registers
#define CSC_COEFF_RB_1_REG                                      0x0B
#define CSC_COEFF_RB_21_REG                                     0x1F
#define HS_POS_CNTRL_1_REG                                      0x22
#define HS_POS_CNTRL_4_REG                                      0x25
#define DE_POS_CNTRL_1_REG                                      0x26
#define DE_POS_CNTRL_10_REG                                     0x2F
#define DE_POS_ADJ_1_REG                                        0x30
#define DE_POS_ADJ_2_REG                                        0x31
#define BIT_REDUCTION_DITHER_REG                        0x36
#define CONTRAST_CNTRL_REG                                      0x3A
#define SATURATION_CNTRL_REG                            0x3B
#define BRIGHTNESS_CNTRL_REG                            0x3C
#define HUE_CNTRL_REG                                           0x3D
#define CP_MISC_CTRL_1_REG                                      0x3E
#define CP_PRE_GAIN_CNTRL_REG                           0x40
#define CSC_COEFFS_1_REG                                        0x52
#define CSC_COEFFS_21_REG                                       0x66
#define EMB_SYNC_ON_ALL_REG                                     0x67
#define CSC_DECIM_CNTRL_REG                                     0x68
#define CP_MISC_CTRL_2_REG                                      0x69
#define CLMP_CNTRL_1_REG                                        0x6C
#define CLMP_CNTRL_2_REG                                        0x6D
#define CLMP_CNTRL_3_REG                                        0x6E
#define CLMP_CNTRL_4_REG                                        0x6F
#define CLMP_CNTRL_5_REG                                        0x70
#define GAIN_CNTRL_1_REG                                        0x71
#define GAIN_CNTRL_6_REG                                        0x76
#define OFFSET_CNTRL_1_REG                                      0x77
#define OFFSET_CNTRL_4_REG                                      0x7A
#define AVCODE_CNTRL_REG                                        0x7B
#define SYNC_CNTRL_1_REG                                        0x7C
#define SYNC_CNTRL_5_REG                                        0x80
#define SYNC_DET_CNTRL_CH1_1_REG                        0x84
#define SYNC_DET_CNTRL_CH1_2_REG                        0x86
#define DE_POS_ADJ_3_REG                                        0x88
#define SYNC_CNTRL_6_REG                                        0x89
#define DE_POS_ADJ_4_REG                                        0x8B
#define DE_POS_ADJ_5_REG                                        0x8C
#define DE_POS_ADJ_6_REG                                        0x8D
#define DE_POS_ADJ_7_REG                                        0x8E
#define SYNC_DET_CNTRL_CH1_4_1_REG                      0x8F
#define SYNC_DET_CNTRL_CH1_4_2_REG                      0x90
#define CP_INTERLACED_REG                                       0x91
#define VS_POS_CNTRL_1_REG                                      0x9A
#define VS_POS_CNTRL_5_REG                                      0x9E
#define FLD_POS_CNTRL_1_REG                                     0x9F
#define FLD_POS_CNTRL_3_REG                                     0xA1
#define SYNC_DET_CNTRL_CH1_RB_1_REG                     0xA3
#define SYNC_DET_CNTRL_CH1_RB_2_REG                     0xA4
#define VBI_POS_CNTRL_1_REG                                     0xA5
#define VBI_POS_CNTRL_6_REG                                     0xAA
#define SYNC_DET_CNTRL_CH1_3_REG                        0xAB
#define SYNC_DET_CNTRL_CH1_4_REG                        0xAC
#define SYNC_DET_CNTRL_CH1_RB_3_REG                     0xB1
#define SYNC_DET_CNTRL_CH1_RB_4_REG                     0xB2
#define SYNC_DET_CNTRL_CH1_RB_5_REG                     0xB3
#define SYNC_DET_CNTRL_CH1_RB_6_1_REG           0xB8
#define SYNC_DET_CNTRL_CH1_RB_6_2_REG           0xB9
#define HDMI_CP_CNTRL_1_REG                                     0xBA
#define COAST_CNTRL_1_REG                                       0xBD
#define CP_MISC_CTRL_3_REG                                      0xBE
#define FR_COLOR_SEL_1_REG                                      0xBF
#define FR_COLOR_SEL_4_REG                                      0xC2
#define CP_MISC_CTRL_4_REG                                      0xC9
#define HDMI_CP_CNTRL_2_REG                                     0xCB
#define CP_MISC_STATUS_1_REG                            0xE0
#define CP_MISC_STATUS_2_REG                            0xE1
#define SYNC_DET_CNTRL_CH1_5_REG                        0xF3
#define CSC_COEFF_SEL_RB_REG                            0xF4
#define CP_MISC_CTRL_5_REG                                      0xF5
#define CP_FREE_RUN_REG                                         0xFF



static
unsigned char g_EDID_items[256] = {
                 0x00, 0xff, 0xff, 0xff, 0x34, 0x00, 0x4e, 0x0b, 0x01, 0x01, 0x80, 0x1b, 0x07, 0x95, 0x54, 0x99,
		 0x0f, 0x54, 0xff, 0x81, 0x81, 0x81, 0x95, 0xa9, 0xb3, 0xd1, 0xd1, 0xf3, 0x80, 0x71, 0x2d, 0x58,
		 0x45, 0xc4, 0x21, 0x0, 0x28, 0x80, 0x70, 0x23, 0x30, 0x36, 0xc4, 0x21, 0x00, 0x00, 0x00, 0x00 ,
		0x72 , 0x20 , 0x61 , 0x74 , 0x72 , 0xa , 0x0 , 0x0 , 0x0 , 0x78 , 0x78 , 0x0 , 0x20 , 0x20 , 0x20 , 0x1 , 0x2 , 0x2f , 0x50 , 0x2 , 0x4 , 0x90 , 0x12 , 0x14 , 0x20 , 0x22 , 0x15 , 0xf , 0x7 , 0x7f , 0x83 , 0x0 , 0x6e , 0xc , 0x20 , 0xf8 , 0x20 , 0x4 , 0x41 , 0xff , 0x39 , 0x18 , 0x38 , 0x40 , 0x2c , 0x0 , 0x8e , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x1 , 0x0 , 0x0 , 0x0 , 0x1 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x1 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x20 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0 , 0x0,
        };
 
